### ISSUE TITLE
Make the playing area 10 by 10

### ISSUE THREAD

**Issue by jelkner** [YBMartini/Browser-Battleship#1]
I want the battleship playing area to be a 10 by 10 matrix, with rows labeled 1 to 10 and columns labeled A to J.

**Comment by mjsir911** [comment]
Should be done in html with tables. Should get Cristian to style table at a later date.

**Comment by YBMartini** [comment]
See my last commit. This issue is resolved.

**Comment by jelkner** [comment]
I just cloned the repository and loaded the index.html file from the src directory in my browser, and I don't see any change.

**Comment by jelkner** [comment]
And in looking at the files, they are all 6 days old.  Did you forget to commit and push your changes?

**Comment by YBMartini** [comment]
There's a development branch, that's what I pushed it to.

**Comment by jelkner** [comment]
Got it.  I'll check that out tomorrow.

**Comment by YBMartini** [comment]
Re-closing the issue, ready for the next one!
